# Generated by Django 4.1.9 on 2024-03-29 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0178_alter_comment_body_alter_organization_about_and_more'),
        ('typeracer', '0003_auto_20220902_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='typoroom',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='is private'),
        ),
        migrations.AddField(
            model_name='typoroom',
            name='mode',
            field=models.CharField(choices=[('solo', 'Solo'), ('multi', 'Multi')], default='multi', max_length=10, verbose_name='mode'),
        ),
        migrations.CreateModel(
            name='TypoRoomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('0', 'Participant'), ('1', 'Spectator'), ('2', 'Waiting')], default='2', max_length=1, verbose_name='action')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='typeracer.typoroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='judge.profile')),
            ],
            options={
                'verbose_name': 'room user',
                'verbose_name_plural': 'room users',
                'unique_together': {('room', 'user')},
            },
        ),
    ]
