# Generated by Django 4.1.9 on 2023-07-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0171_remove_profile_is_totp_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the curriculum', max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Description of the curriculum', verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='PublicProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Order of the problem in the curriculum', verbose_name='order')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_problems', to='judge.curriculum', verbose_name='curriculum')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='judge.problem', verbose_name='problem')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('curriculum', 'problem')},
            },
        ),
        migrations.CreateModel(
            name='CurriculumContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Description of the contest in the curriculum', max_length=255, verbose_name='description')),
                ('order', models.IntegerField(default=0, help_text='Order of the contest in the curriculum', verbose_name='order')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='judge.contest', verbose_name='contest')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_contests', to='judge.curriculum', verbose_name='curriculum')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('curriculum', 'contest')},
            },
        ),
        migrations.AddField(
            model_name='curriculum',
            name='contests',
            field=models.ManyToManyField(blank=True, help_text='Contests in the curriculum', through='judge.CurriculumContest', to='judge.contest', verbose_name='contests'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='problems',
            field=models.ManyToManyField(blank=True, help_text='Problems in the curriculum', through='judge.PublicProblem', to='judge.problem', verbose_name='problems'),
        ),
    ]
