# Generated by Django 4.1.9 on 2023-07-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0172_curriculum_publicproblem_curriculumcontest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='super_admin',
            field=models.BooleanField(default=False, verbose_name='super admin'),
        ),
    ]
