# Generated by Django 4.1.9 on 2023-11-28 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0173_profile_super_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogDownloadTestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='case position')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem', verbose_name='problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.profile', verbose_name='user')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
