# Generated by Django 4.1.9 on 2023-11-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0174_logdownloadtestcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_download_all_testcases',
            field=models.BooleanField(default=False, verbose_name='can download all testcases'),
        ),
    ]
