# Generated by Django 4.1.9 on 2023-12-13 14:10

from django.db import migrations, models
import judge.models.problem
import judge.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0175_profile_can_download_all_testcases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=8192, validators=[judge.models.problem.disallowed_characters_validator], verbose_name='body of comment'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='about',
            field=models.TextField(validators=[judge.models.profile.disallowed_characters_validator], verbose_name='organization description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, null=True, validators=[judge.models.profile.disallowed_characters_validator], verbose_name='self-description'),
        ),
    ]
