# Generated by Django 4.1.9 on 2024-01-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0175_profile_can_download_all_testcases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionsource',
            name='source',
            field=models.TextField(db_collation='utf8mb4_unicode_ci', max_length=65536, verbose_name='source code'),
        ),
    ]
