# Generated by Django 4.1.9 on 2023-12-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0176_alter_comment_body_alter_organization_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionsource',
            name='source',
            field=models.TextField(max_length=65536, verbose_name='source code'),
        ),
    ]
