# Generated by Django 4.1.9 on 2024-01-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0176_alter_submissionsource_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestproblem',
            name='limit_point',
            field=models.IntegerField(default=0, verbose_name='limit point'),
        ),
    ]
