# Generated by Django 4.1.9 on 2024-01-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0177_contestproblem_limit_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(db_collation='utf8mb4_unicode_ci', max_length=8192, verbose_name='body of comment'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='about',
            field=models.TextField(db_collation='utf8mb4_unicode_ci', verbose_name='organization description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True, verbose_name='self-description'),
        ),
    ]
