# Generated by Django 4.1.9 on 2024-06-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0178_alter_comment_body_alter_organization_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='fastio',
            field=models.BooleanField(default=False, verbose_name='Fast IO'),
        ),
    ]
