# Generated by Django 4.1.9 on 2024-07-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0180_alter_problem_memory_limit_alter_problem_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestproblem',
            name='limit_point',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='limit point'),
        ),
    ]
