# Generated by Django 4.1.9 on 2024-07-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0181_alter_contestproblem_limit_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='forbidden_words',
            field=models.TextField(blank=True, verbose_name='forbidden words'),
        ),
    ]
