# Generated by Django 4.1.9 on 2024-07-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0183_alter_contest_forbidden_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationrequest',
            name='state',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected'), ('L', 'Leaved'), ('K', 'Kicked')], max_length=1, verbose_name='state'),
        ),
    ]
