# Generated by Django 4.1.13 on 2024-08-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0185_alter_contest_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestproblem',
            name='first_accept',
        ),
    ]
