# Generated by Django 4.1.13 on 2024-09-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0186_remove_contestproblem_first_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='approved'),
        ),
    ]
