# Generated by Django 4.1.9 on 2024-10-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0187_problem_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='format_name',
            field=models.CharField(choices=[('atcoder', 'AtCoder'), ('default', 'Default'), ('default_limit', 'Default Limit'), ('ecoo', 'ECOO'), ('icpc', 'ICPC'), ('ioi', 'IOI (pre-2016)'), ('ioi16', 'IOI'), ('tmath', 'Tmath')], default='default', help_text='The contest format module to use.', max_length=32, verbose_name='contest format'),
        ),
        migrations.AlterField(
            model_name='samplecontest',
            name='format_name',
            field=models.CharField(choices=[('atcoder', 'AtCoder'), ('default', 'Default'), ('default_limit', 'Default Limit'), ('ecoo', 'ECOO'), ('icpc', 'ICPC'), ('ioi', 'IOI (pre-2016)'), ('ioi16', 'IOI'), ('tmath', 'Tmath')], default='default', help_text='The contest format module to use.', max_length=32, verbose_name='contest format'),
        ),
    ]
